import { useMemo, useState } from 'react'
import { ArrowUpRight, Search, SlidersHorizontal, Star, ChevronDown, FileCheck2 } from 'lucide-react'
import { BRAND } from '../../lib/brand'

// Fictional examples, isolated from authenticated account data and live API results.
const examples = [
  { name: 'Northstar Components', sector: 'Industrials', country: 'US', score: 684, coverage: 72, sources: 5, signal: 'Registry match', history: [41,44,43,49,47,56,54,60,65,64,68], evidence: 'Entity identity matched in the illustrative registry record.' },
  { name: 'Meridian Logistics', sector: 'Logistics', country: 'US', score: 612, coverage: 64, sources: 4, signal: 'Award activity', history: [53,51,56,53,52,58,56,59,61,60,61], evidence: 'Illustrative procurement awards provide activity context.' },
  { name: 'Cedar Health Systems', sector: 'Healthcare', country: 'US', score: null, coverage: 28, sources: 2, signal: 'Evidence gap', history: [21,24,20,26,24,28,26,29,27,28,28], evidence: 'Insufficient evidence. A score is withheld rather than inferred.' },
  { name: 'Atlas Precision', sector: 'Industrials', country: 'US', score: 731, coverage: 81, sources: 6, signal: 'Filing update', history: [59,63,62,68,65,69,71,68,74,72,73], evidence: 'Illustrative filing adds corroborating entity information.' },
  { name: 'Willow Foods', sector: 'Consumer', country: 'US', score: 548, coverage: 58, sources: 3, signal: 'Coverage change', history: [62,61,58,60,57,59,55,56,53,55,55], evidence: 'Coverage varies with source availability. Missing feeds remain unavailable.' },
]
function Spark({ values, large = false }) {
 const pts = values.map((v,i)=>`${i*10},${100-v}`).join(' ')
 return <svg className={large?'terminal-chart':'sparkline'} viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Illustrative evidence trend"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth={large?0.8:2} vectorEffect="non-scaling-stroke" /></svg>
}
export default function ResearchTerminal({ compact = false }) {
 const [query,setQuery]=useState(''), [sector,setSector]=useState('All sectors'), [selected,setSelected]=useState(examples[0]), [saved,setSaved]=useState([]), [onlySaved,setOnlySaved]=useState(false), [sort,setSort]=useState(false), [tab,setTab]=useState('Evidence')
 const rows=useMemo(()=>examples.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&(sector==='All sectors'||x.sector===sector)&&(!onlySaved||saved.includes(x.name))).sort((a,b)=>sort?(b.score??-1)-(a.score??-1):0),[query,sector,onlySaved,saved,sort])
 const toggle=(name)=>setSaved(s=>s.includes(name)?s.filter(x=>x!==name):[...s,name])
 return <section className={`research-terminal ${compact?'compact-terminal':''}`} aria-label="Interactive illustrative research workspace">
  <div className="terminal-top"><span className="terminal-dot"/><strong>RESEARCH DESK</strong><span className="terminal-divider">/</span><span>Private companies</span><span className="demo-label">ILLUSTRATIVE DEMO · FICTIONAL DATA</span></div>
  <div className="terminal-metrics"><div><small>COMPANIES IN VIEW</small><strong>{rows.length.toString().padStart(2,'0')}</strong></div><div><small>RATED EXAMPLES</small><strong>{rows.filter(x=>x.score!==null).length.toString().padStart(2,'0')}</strong></div><div><small>MODEL RANGE</small><strong>0–1,000</strong></div><div><small>SAVED THIS SESSION</small><strong>{saved.length.toString().padStart(2,'0')}</strong></div></div>
  <div className="terminal-toolbar"><label className="terminal-search"><Search size={15}/><input aria-label="Filter example companies" placeholder="Find a company…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="sector-select"><SlidersHorizontal size={14}/><select aria-label="Filter by sector" value={sector} onChange={e=>setSector(e.target.value)}>{['All sectors','Industrials','Logistics','Healthcare','Consumer'].map(x=><option key={x}>{x}</option>)}</select></label><button className={onlySaved?'terminal-filter active':'terminal-filter'} onClick={()=>setOnlySaved(!onlySaved)} aria-pressed={onlySaved}><Star size={14}/> Saved</button></div>
  <div className="terminal-body"><div className="terminal-table-wrap"><table className="terminal-table"><thead><tr><th>Company</th><th><button onClick={()=>setSort(!sort)} aria-label="Toggle score sorting">{BRAND.score}<ChevronDown size={12}/></button></th><th>Coverage</th><th>Trend*</th><th>Save</th></tr></thead><tbody>{rows.map(c=><tr key={c.name} className={selected.name===c.name?'selected':''}><td><button className="company-select" onClick={()=>setSelected(c)}><strong>{c.name}</strong><small>{c.sector} / {c.country}</small></button></td><td className={c.score===null?'unrated-cell':'score-cell'}>{c.score??'Unrated'}</td><td><span>{c.coverage}%</span><div className="coverage-mini"><i style={{width:`${c.coverage}%`}}/></div></td><td><Spark values={c.history}/></td><td><button className="save-example" aria-label={`${saved.includes(c.name)?'Unsave':'Save'} ${c.name}`} aria-pressed={saved.includes(c.name)} onClick={()=>toggle(c.name)}><Star size={14} fill={saved.includes(c.name)?'currentColor':'none'}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="terminal-empty">No matching examples. Change your search or filters.</p>}<div className="terminal-table-foot">{rows.length} examples <span>*Illustrative trend, not live observations</span></div></div>
  <aside className="terminal-detail"><div className="detail-kicker"><FileCheck2 size={14}/> EVIDENCE INSPECTOR</div><h3>{selected.name}</h3><p>{selected.sector} · United States</p><div className="inspector-score"><strong>{selected.score??'—'}</strong><span>{BRAND.score}<br/>{selected.score===null?'Insufficient evidence':'Illustrative / 1,000'}</span></div><div className="inspector-chart"><Spark values={selected.history} large/></div><div className="terminal-tabs" role="tablist" aria-label="Company detail">{['Evidence','Method'].map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="inspector-copy" role="tabpanel">{tab==='Evidence'?<><strong>{selected.signal}</strong><p>{selected.evidence}</p><div className="inspector-row"><span>Evidence coverage</span><b>{selected.coverage}%</b></div><div className="inspector-row"><span>Example sources</span><b>{selected.sources}</b></div></>:<><strong>Evidence before confidence</strong><p>Scores depend on source quality, entity matching and coverage. Missing evidence can prevent a rating. Research scores are not default probabilities.</p></>}</div></aside></div>
  {!compact&&<div className="demo-disclosure"><ArrowUpRight size={14}/> Explore filters, company selection and saves. Demo saves last only for this page session. Sign in to research real companies.</div>}
 </section>
}
