"""add MFA consent and scheduled notification state"""
from alembic import op
import sqlalchemy as sa

revision = '5da46a24aab7'
down_revision = '7a9b2795b255'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_counter', sa.Integer(), nullable=False),
    sa.Column('recovery_hashes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('provider_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('connection_id', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', 'connection_id')
    )
    op.create_index(op.f('ix_provider_consents_organization_id'), 'provider_consents', ['organization_id'], unique=False)
    op.create_table('workspace_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_job_id', sa.Integer(), nullable=True),
    sa.Column('previous', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_monitors_next_run'), 'workspace_monitors', ['next_run'], unique=False)
    op.create_index(op.f('ix_workspace_monitors_organization_id'), 'workspace_monitors', ['organization_id'], unique=False)
    op.create_table('consent_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('encrypted_payload', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['provider_consents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id', 'cache_key')
    )
    op.create_index(op.f('ix_consent_payloads_consent_id'), 'consent_payloads', ['consent_id'], unique=False)
    op.create_index(op.f('ix_consent_payloads_expires_at'), 'consent_payloads', ['expires_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['organization_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'channel', 'destination')
    )
    op.create_index(op.f('ix_notification_deliveries_event_id'), 'notification_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_organization_id'), 'notification_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_state'), 'notification_deliveries', ['state'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_state'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_organization_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_consent_payloads_expires_at'), table_name='consent_payloads')
    op.drop_index(op.f('ix_consent_payloads_consent_id'), table_name='consent_payloads')
    op.drop_table('consent_payloads')
    op.drop_index(op.f('ix_workspace_monitors_organization_id'), table_name='workspace_monitors')
    op.drop_index(op.f('ix_workspace_monitors_next_run'), table_name='workspace_monitors')
    op.drop_table('workspace_monitors')
    op.drop_index(op.f('ix_provider_consents_organization_id'), table_name='provider_consents')
    op.drop_table('provider_consents')
    op.drop_table('mfa_credentials')
    # ### end Alembic commands ###
