"""add isolated organizations and durable work queue"""
from alembic import op
import sqlalchemy as sa

revision = '7a9b2795b255'
down_revision = '20260920_0005'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('organization_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_audit_created_at'), 'organization_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_audit_organization_id'), 'organization_audit', ['organization_id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('token_hash', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_table('organization_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('key_hash', sa.String(length=80), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_organization_keys_organization_id'), 'organization_keys', ['organization_id'], unique=False)
    op.create_table('organization_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('dedupe_key', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kind', 'dedupe_key')
    )
    op.create_index(op.f('ix_organization_resources_created_at'), 'organization_resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_resources_kind'), 'organization_resources', ['kind'], unique=False)
    op.create_index(op.f('ix_organization_resources_organization_id'), 'organization_resources', ['organization_id'], unique=False)
    op.create_table('work_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('batch_key', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_work_jobs_available_at'), 'work_jobs', ['available_at'], unique=False)
    op.create_index(op.f('ix_work_jobs_batch_key'), 'work_jobs', ['batch_key'], unique=False)
    op.create_index(op.f('ix_work_jobs_organization_id'), 'work_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_jobs_state'), 'work_jobs', ['state'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_jobs_state'), table_name='work_jobs')
    op.drop_index(op.f('ix_work_jobs_organization_id'), table_name='work_jobs')
    op.drop_index(op.f('ix_work_jobs_batch_key'), table_name='work_jobs')
    op.drop_index(op.f('ix_work_jobs_available_at'), table_name='work_jobs')
    op.drop_table('work_jobs')
    op.drop_index(op.f('ix_organization_resources_organization_id'), table_name='organization_resources')
    op.drop_index(op.f('ix_organization_resources_kind'), table_name='organization_resources')
    op.drop_index(op.f('ix_organization_resources_created_at'), table_name='organization_resources')
    op.drop_table('organization_resources')
    op.drop_index(op.f('ix_organization_keys_organization_id'), table_name='organization_keys')
    op.drop_table('organization_keys')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_organization_audit_organization_id'), table_name='organization_audit')
    op.drop_index(op.f('ix_organization_audit_created_at'), table_name='organization_audit')
    op.drop_table('organization_audit')
    op.drop_table('memberships')
    op.drop_table('organizations')
    # ### end Alembic commands ###
