import { useEffect, useState } from 'react'
import { apiRequest } from '../../api/client'
import ErrorNotice from '../common/ErrorNotice'
export default function WorkspaceOperations({ organization }) {
 const [monitors,setMonitors]=useState([]),[deliveries,setDeliveries]=useState([]),[corrections,setCorrections]=useState([])
 const [company,setCompany]=useState(''),[reportId,setReportId]=useState(''),[reason,setReason]=useState(''),[password,setPassword]=useState('')
 const [required,setRequired]=useState(Boolean(organization.require_mfa)),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const root=`/api/organizations/${organization.id}`
 async function refresh(){const [m,d,c]=await Promise.all([apiRequest(root+'/monitoring'),apiRequest(root+'/notifications'),apiRequest(root+'/resources?kind=correction')]);setMonitors(m);setDeliveries(d);setCorrections(c.items)}
 useEffect(()=>{let active=true;Promise.all([apiRequest(root+'/monitoring'),apiRequest(root+'/notifications'),apiRequest(root+'/resources?kind=correction')]).then(([m,d,c])=>{if(active){setMonitors(m);setDeliveries(d);setCorrections(c.items)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[root])
 async function act(path,method,body){setBusy(true);setError('');try{await apiRequest(root+path,{method,...(body?{body:JSON.stringify(body)}:{})});await refresh();setPassword('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><ErrorNotice message={error}/>
 <section className="panel form-stack"><h2>Scheduled monitoring</h2><p>Weekly reevaluation checks for material changes. Delivery history shows successful and failed attempts.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();act('/monitoring','POST',{legal_name:company})}}><label>Company to monitor<input required maxLength={180} value={company} onChange={e=>setCompany(e.target.value)}/></label><button className="btn" disabled={busy}>Schedule monitoring</button></form>{monitors.length===0&&<p>No monitored companies.</p>}{monitors.map(m=><div key={m.id}>{m.identity.legal_name} · {m.active?'Active':'Disabled'} · Next run {new Date(m.next_run).toLocaleString()} {m.active&&<button className="btn" disabled={busy} onClick={()=>act(`/monitoring/${m.id}`,'DELETE')}>Stop monitoring</button>}</div>)}<h3>Notification history</h3>{deliveries.length===0&&<p>No notifications yet.</p>}{deliveries.map(d=><p key={d.id}>{d.channel} · {d.state} · {d.attempts} attempts{d.last_attempt_at&&` · Last attempted ${new Date(d.last_attempt_at).toLocaleString()}`}{d.delivered_at&&` · Delivered ${new Date(d.delivered_at).toLocaleString()}`}{d.error_code&&` · ${d.error_code}`}</p>)}<button className="btn" disabled={busy} onClick={()=>{setBusy(true);refresh().catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>Refresh monitoring</button></section>
 <section className="panel form-stack"><h2>Report corrections</h2><form className="form-stack" onSubmit={e=>{e.preventDefault();act('/corrections','POST',{report_id:Number(reportId),reason})}}><label>Report ID<input type="number" min="1" required value={reportId} onChange={e=>setReportId(e.target.value)}/></label><label>Evidence to review<textarea minLength={10} maxLength={4000} required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn" disabled={busy}>Submit correction</button></form>{corrections.length===0&&<p>No correction requests.</p>}{corrections.map(c=><details key={c.id}><summary>Report {c.payload.report_id} · {c.payload.status}</summary><p>{c.payload.reason}</p></details>)}</section>
 {organization.role==='owner'&&<section className="panel form-stack"><h2>Workspace security</h2><p>Enroll your own account in MFA before requiring it for members. Members can reach their account settings to enroll.</p><label><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>Require MFA for workspace access</label><label>Confirm current password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn" disabled={busy||!password} onClick={()=>act('/security','PATCH',{require_mfa:required,password})}>Save security policy</button></section>}
 </>
}
