import { ArrowRight, ArrowUpRight, Database, ScanSearch, Layers3, ShieldCheck } from 'lucide-react'
import BrandMark from '../components/common/BrandMark'
import ResearchTerminal from '../components/dashboard/ResearchTerminal'
import { BRAND } from '../lib/brand'
import { Link } from '../router'
export default function Landing(){return <main className="public-page terminal-landing">
 <nav className="public-nav"><Link to="/" className="brand"><BrandMark/><strong>{BRAND.name}<span className="brand-period">.</span></strong></Link><div className="landing-nav-links"><a href="#workspace">The workspace</a><a href="#method">Our approach</a></div><div><Link to="/login" className="btn btn-ghost">Log in</Link><Link to="/signup" className="btn btn-primary">Start researching <ArrowUpRight size={15}/></Link></div></nav>
 <section className="terminal-hero"><div className="hero-overline"><span className="terminal-dot"/> PRIVATE COMPANY INTELLIGENCE</div><h1>A clearer view of<br/>the companies <em>off-market.</em></h1><p>Follow the evidence behind private companies. Bring fragmented public records into one focused research desk, with {BRAND.score} and the sources behind it.</p><div className="hero-actions"><Link to="/signup" className="btn btn-primary">Open your research desk <ArrowRight size={16}/></Link><a href="#workspace" className="btn btn-ghost">Explore the demo</a></div><div className="hero-note">Evidence-weighted research. Coverage visible. Uncertainty included.</div></section>
 <section id="workspace" className="landing-workspace"><div className="section-caption"><span>01 / YOUR RESEARCH, IN FOCUS</span><span>Interactive product illustration</span></div><ResearchTerminal/></section>
 <section className="product-numbers"><div><strong>0–1,000</strong><span>PerpScore research range</span></div><div><strong>4</strong><span>Companies in a peer comparison</span></div><div><strong>1,000</strong><span>CSV rows per batch in the pilot</span></div><div><strong>1 desk</strong><span>Reports, evidence and watchlists</span></div></section>
 <section className="approach-section" id="method"><div><div className="hero-overline">02 / THE PERPSCORE APPROACH</div><h2>The number starts<br/>with the evidence.</h2><p>A private company is more than a search result. Inspect what matches, what is current, and what is still missing before drawing a conclusion.</p><Link to="/signup" className="text-link">Build your first research brief <ArrowUpRight size={15}/></Link></div><div className="approach-list">{[[ScanSearch,'Resolve the company','Match the legal entity before interpreting its signals. Ambiguous matches stay visible.'],[Database,'Inspect the source','Review provenance and coverage. Unavailable financial or commercial feeds remain unavailable.'],[Layers3,'Compare consistently','Apply the same research model across up to four companies, then save the names worth following.'],[ShieldCheck,'Keep the limits visible','PerpScore is a research indicator. It is not a credit rating or a validated probability of default.']].map(([Icon,title,copy])=><article key={title}><Icon size={20}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
 <section className="closing-cta"><div><div className="hero-overline">RESEARCH WITH CONTEXT</div><h2>Make your next question<br/>a better-informed one.</h2></div><Link to="/signup" className="btn btn-primary">Create your workspace <ArrowRight size={16}/></Link></section>
 <footer className="public-footer"><strong>{BRAND.name}.</strong><span>Research MVP. Source availability varies. No investment or lending advice.</span><Link to="/login">Open workspace ↗</Link></footer>
 </main>}
