import { useEffect, useState } from 'react'
import { apiRequest } from '../api/client'
import PageHeader from '../components/common/PageHeader'
export default function ResearchControls(){
  const [reports,setReports]=useState([]),[disputes,setDisputes]=useState([]),[subs,setSubs]=useState([]),[events,setEvents]=useState([]),[message,setMessage]=useState('')
  const [reportId,setReportId]=useState(''),[details,setDetails]=useState(''),[reason,setReason]=useState('wrong_entity'),[company,setCompany]=useState('')
  async function load(){const [r,d,s,e]=await Promise.all([apiRequest('/api/reports'),apiRequest('/api/corrections'),apiRequest('/api/monitoring'),apiRequest('/api/monitoring/events')]);setReports(r);setDisputes(d);setSubs(s);setEvents(e)}
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
  async function dispute(e){e.preventDefault();try{await apiRequest('/api/corrections',{method:'POST',body:JSON.stringify({report_id:Number(reportId),reason,details})});setDetails('');setMessage('Correction submitted for review. Reports are not changed automatically.');await load()}catch(e){setMessage(e.message)}}
  async function monitor(e){e.preventDefault();try{await apiRequest('/api/monitoring',{method:'POST',body:JSON.stringify({legal_name:company})});setCompany('');setMessage('Subscription saved. Reevaluation requires an active deployment scheduler.');await load()}catch(e){setMessage(e.message)}}
  return <div className="page-stack"><PageHeader eyebrow="Pilot" title="Research review">Request corrections and manage scheduled research checks.</PageHeader>{message&&<p role="status">{message}</p>}
    <form className="panel form-stack" onSubmit={dispute}><h2>Report an issue</h2><label>Saved report<select required value={reportId} onChange={e=>setReportId(e.target.value)}><option value="">Select a report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.company_name} — {r.created_at}</option>)}</select></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}>{['wrong_entity','incorrect_address','incorrect_information','wrong_legal_event','stale_evidence','incorrect_source','other'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Details<textarea required minLength={10} maxLength={4000} value={details} onChange={e=>setDetails(e.target.value)}/></label><button className="btn btn-primary">Submit for review</button>{disputes.map(d=><p key={d.id}>Issue {d.id}: {d.status}</p>)}</form>
    <form className="panel form-stack" onSubmit={monitor}><h2>Scheduled checks</h2><p>Weekly reevaluation foundation. Scheduler activation and reliable delivery are deployment requirements. This is not real-time monitoring.</p><label>Company name<input value={company} required minLength={2} onChange={e=>setCompany(e.target.value)}/></label><button className="btn btn-primary">Save subscription</button>{subs.map(s=><div key={s.id}>{s.identity.legal_name}<button type="button" className="btn btn-ghost" onClick={async()=>{try{await apiRequest(`/api/monitoring/${s.id}`,{method:'DELETE'});await load()}catch(e){setMessage(e.message)}}}>Remove</button></div>)}</form>
    <section className="panel"><h2>Change events</h2>{events.length?events.map(e=><p key={e.id}>{e.created_at}: {e.payload.reasons.join(', ')}</p>):<p>No change events recorded.</p>}</section>
  </div>
}
